### ISSUE TITLE
Can i use this as a linux library ( .so)?

### ISSUE THREAD

**Issue by timwhitez** [trustedsec/ELFLoader#1]
Can i use this as a linux library ( .so)?

**Comment by kev169** [comment]
I haven't tested it out or made a make target for it, but should be able to with a few modifications. I'll try it out when I get time this next week.

**Comment by timwhitez** [comment]
thx so much!

**Comment by kev169** [comment]
Committed up an example of how to build as a shared object, and the code to call it in runner.c. Closing for now.
